spring:
  cloud:
    config:
      server:
        native:
          search-location: classpath:/shared
  profiles:
    active: native
  security:
    user:
      password: ${CONFIG_SERVICE_PASSWORD}

server:
  port: 8888